# Generated by Django 6.0 on 2026-01-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_managment_app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task_managment_app1.team",
            ),
        ),
    ]
