# Generated by Django 6.0 on 2026-01-07 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_managment_app1", "0003_remove_worker_email_alter_worker_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="name",
        ),
    ]
