# Generated by Django 5.2.6 on 2026-01-13 10:47

import task_managment_app1.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_managment_app1", "0004_remove_worker_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="targetDate",
            field=models.DateField(
                validators=[task_managment_app1.models.future_date_validator]
            ),
        ),
    ]
