# Generated by Django 6.0 on 2026-01-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_managment_app1", "0005_alter_task_targetdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="task_managment_app1.team",
            ),
        ),
    ]
