# Generated by Django 6.0 on 2026-01-13 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_managment_app1", "0006_alter_task_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="task_managment_app1.team",
            ),
        ),
    ]
