# Generated by Django 6.0 on 2026-01-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_managment_app1", "0007_alter_task_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("WORKER", "Worker"),
                    ("SUPER_ADMIN", "Super_Admin"),
                ],
                default="WORKER",
                max_length=50,
            ),
        ),
    ]
